// Single source of truth for every real file the mirror needs to have.
// Used by both crawl.mjs (to download them) and verify.mjs (to check them),
// so the two can never drift into two different lists of "what's real".
export const SEED_FILES = [
  // --- root ---
  '/index.html',
  '/logo.svg',
  '/share-1.png',
  '/favicon/site.webmanifest',
  '/favicon/favicon-96x96.png',
  '/favicon/favicon.svg',
  '/favicon/favicon.ico',
  '/favicon/apple-touch-icon.png',
  '/favicon/web-app-manifest-192x192.png',
  '/favicon/web-app-manifest-512x512.png',

  // --- js chunks ---
  '/assets/index-DjTFcfxW.js',
  '/assets/basis.worker.js',
  '/assets/basis_transcoder.js',
  '/assets/basis_transcoder.wasm',
  '/assets/arrow-left-C7jeBWlv.js',
  '/assets/arrow-right-DUyuFG79.js',
  '/assets/check-B-2exQel.js',
  '/assets/comma-Cth_LlsD.js',
  '/assets/cross-B0spWP7d.js',
  '/assets/download-DM8QDz7e.js',
  '/assets/lightning-Cba1wdxJ.js',
  '/assets/base-MwNZ0Omb.js',
  '/assets/randomize-bhz1IDAl.js',
  '/assets/share-CKE7T_sZ.js',
  '/assets/versus-background-Cmn-ySuf.js',
  '/assets/versus-foreground-DCIy8lIF.js',

  // --- css ---
  '/assets/index-BSwuqJ-_.css',

  // --- fonts ---
  '/assets/aaksimosi-DjvOQu72.woff2',
  '/assets/bangers-DeHY8Ncq.woff2',
  '/assets/poppins-regular-cpxAROuN.woff2',

  // --- glb ---
  '/assets/avatar-bUMLPl_Q.glb',
  '/assets/grid-WSOFoBNr.glb',
  '/assets/lightning-CCwfz3l8.glb',
  '/assets/processed-BEDFlmDO.glb',
  '/assets/shapes-80-xMobG.glb',

  // --- webgl textures ---
  '/assets/dragndrop-DNT5_CGs.png',
  '/assets/heart-Bk4K9W7K.png',
  '/assets/lightning-4grXkpr2.png',
  '/assets/sleep-B4d8uCDt.png',
  '/assets/stroke_transition-2hqvpxUU.png',
  '/assets/stroke_transition_2-kiMmbJDV.png',
  '/assets/tears-CC8MtNpa.png',

  // --- sdf fonts ---
  // note: only the .json manifest is a real file for each font; there is
  // no matching aaksimosi-C3BzEqTF.js / bangers-DpM2yeyv.js chunk (that was
  // a stale seed entry that resolved to the SPA fallback, not a real asset)
  '/assets/aaksimosi-C3BzEqTF.json',
  '/assets/aaksimosi-DwTuhxOd.png',
  '/assets/bangers-DpM2yeyv.json',
  '/assets/bangers-D4QO0oTV.png',

  // --- audio ---
  // note: game_audio-sd2rnhTe.js doesn't exist either, same as above
  '/assets/game_audio-sd2rnhTe.json',
  '/assets/game_audio-Ve9oyfJI.mp3',

  // --- ui images ---
  '/assets/rotate-avatar-UsFQ9y-m.png',
  '/assets/rotate-bg-DII71BQX.jpg',
  '/assets/default-DVuH2Ed6.png',
  '/assets/hover-8pwqRDRl.png',
  '/assets/o-dAMcZUkb.png',
  '/assets/x-DZBg_-zW.png',
  '/assets/background-desktop-CClWkPTW.png',
  '/assets/background-mobile-SPRgPPTg.png',
  '/assets/cookie-background-desktop-BJckyl82.png',
  '/assets/cookie-desktop-w3RA3aXh.png',
  '/assets/cookie-background-mobile-C9hXSMsW.png',
  '/assets/cookie-mobile-DzoMXazb.png',

  // --- configurator ---
  '/assets/B0-DFxftU9o.png',
  '/assets/B1-B0s62fYe.png',
  '/assets/B2-B3bjq5Uy.png',
  '/assets/B3-BffhHJU1.png',
  '/assets/B4-Uwj5QJx2.png',
  '/assets/B5-Cg2_Ryz4.png',
  '/assets/B6-8tKqBHcQ.png',
  '/assets/B7-BJ_iWpI9.png',
  '/assets/B8-BTBuFrH8.png',
  '/assets/B9-wtABdzSn.png',
  '/assets/D1-C3tMxePw.png',
  '/assets/D2-DUTH7npU.png',
  '/assets/D3-DfzmNrZf.png',
  '/assets/D4-dILi-X3_.png',
  '/assets/D5-Onipvdzz.png',
  '/assets/E0-BDD50b65.png',
  '/assets/E1-Bxy3Zih9.png',
  '/assets/E2-BypMnUCB.png',
  '/assets/E3-CeoaZStJ.png',
  '/assets/E4-CfZNbH83.png',
  '/assets/E5-DMEmHWip.png',
  '/assets/E6-Cvt8gZXU.png',
  '/assets/E7-B1J0lljO.png',
  '/assets/E8-Dw3slp2O.png',
  '/assets/E9-DHDRVx3y.png',
  '/assets/F1-H2-hAhrd.png',
  '/assets/F2-ConkQhto.png',
  '/assets/F3-DzWnFVPy.png',
  '/assets/F4-CGPOqJJN.png',
  '/assets/F5-DiC1xa47.png',
  '/assets/H1-DTTJy9Sz.png',
  '/assets/H10-DzgcqZUW.png',
  '/assets/H11-fF7kgHfq.png',
  '/assets/H12-BHXUvxKY.png',
  '/assets/H13-D5OzBsSp.png',
  '/assets/H14-BNH4C3Gi.png',
  '/assets/H2-BJCxmuvn.png',
  '/assets/H3-WMx58srB.png',
  '/assets/H4-DST_ItvZ.png',
  '/assets/H5-CQ_-nlHO.png',
  '/assets/H6-BbcpU2Eo.png',
  '/assets/H7-DrhBk9TK.png',
  '/assets/H8-Bk2401L6.png',
  '/assets/H9-9Wj_cCvo.png',
  '/assets/J1-C27iZhfW.png',
  '/assets/J2-CndpjxIo.png',
  '/assets/J3-C_eVWHHu.png',
  '/assets/J4-BiwHo6-p.png',
  '/assets/J5-DbDZFY4h.png',
  '/assets/J6-BS4yZuvO.png',
  '/assets/N2-CmGFzWDv.png',
  '/assets/N3-BzbnoIHy.png',
  '/assets/N4-BVGiBiZI.png',
  '/assets/T1-ROYWNVIs.png',
  '/assets/T2-DwHpoWqi.png',
  '/assets/T3-CD1mUsaP.png',
  '/assets/T4-D6frEu1V.png',
  '/assets/pulse_0-D-X61g-D.png',
  '/assets/pulse_1-DOjGQbBv.png',
  '/assets/pulse_2-SRnGdOjW.png',
  '/assets/pulse_3-C3nWXhjn.png',
  '/assets/pulse_4-B2t4GiMd.png',
  '/assets/pulse_white_0-CLnIUUx8.png',
  '/assets/pulse_white_1-DdRVB5Jk.png',
  '/assets/pulse_white_2-sCFYPMwc.png',
  '/assets/pulse_white_3-C3DyS3Xg.png',
  '/assets/pulse_white_4-BLojzLc2.png',
  '/assets/play_0-BKmhkj_6.png',
  '/assets/play_1-CjeZflYa.png',
  '/assets/play_2-i9ORMu1-.png',
  '/assets/play_3-YLxiEd5K.png',
  '/assets/play_white_0-CIHxJsQd.png',
  '/assets/play_white_1-BYibLCHM.png',
  '/assets/play_white_2-D30gyIqI.png',
  '/assets/play_white_3-CrSMrOQ3.png',

  // --- versus / result icons (30 team members x2 + generic) ---
  ...versusChunks(),
  '/assets/win-DMFjlf5t.js',
  '/assets/win_b-BlmIENL7.js',
  '/assets/lose-B1rPbQCJ.js',
  '/assets/lose_b-DB0jMgeE.js',
  '/assets/draw-B6oDcTHG.js',
  '/assets/draw_b-CYctGT3o.js',
  '/assets/you-cocwCuf6.js',
  '/assets/you_b-0K3diT4K.js',
].map((p) => p.replace(/^\//, ''))

function versusChunks() {
  const members = [
    'adrienl', 'anthonym', 'antoineu', 'aurelienc', 'camillec', 'cassandreb',
    'connorh', 'florentinm', 'francoisc', 'francoises', 'gauthierp', 'gregoryb',
    'helenet', 'jeremiec', 'jeromel', 'julienv', 'manonb', 'marieelisea',
    'mathiasr', 'nicolasr', 'nilsl', 'pierrel', 'remib', 'romainp',
    'sachag', 'sarahc', 'solener', 'thomasr', 'valentinm', 'vincents',
  ]
  const hashes = [
    ['M9Nfaivy', 'D75yyPDL'], ['DkdUpenk', 'csK5V3xA'], ['DpqUN3B7', 'YILGpawK'],
    ['2Z5MwrGE', 'BSoHgv5F'], ['NAk8zoZR', 'tjCfpL8j'], ['DaRCBv_Q', 'jxCUsxKP'],
    ['DwBefyz7', 'CakU7z_L'], ['C_BSn9GL', 'CBYTmLjv'], ['PKvg02gz', 'dULGfrLH'],
    ['BnNVW4AX', 'Bohkk3Kh'], ['B0nbLVmN', 'C5ooJMiy'], ['DpwY59Bj', 'C3ZZ0m1E'],
    ['B8JC8OOM', 'BUGyi5_O'], ['BYVhpi-I', 'Dl47sCOb'], ['ACN0GV9q', 'Cin4icyR'],
    ['5NFmIxAk', 'DbFvYkUK'], ['CTjLh5i_', 'B-e17era'], ['TjUlBvgo', 'CIJXQgIs'],
    ['CpmOZixN', 'BzZE5asb'], ['CfdKaiJD', 'B23fyufA'], ['BHsc6MkV', 'DSNHN-cZ'],
    ['C9CGbf0e', 'BDW1q5uM'], ['BYQxSiV7', 'CxIr4vDi'], ['DHS4nBMM', 'CfhtcN-Y'],
    ['Cu3Mb6vD', 'DqsECZ9_'], ['DGFDukEP', 'C3vAeN_v'], ['Fm8_av5U', 'DLvI-e11'],
    ['DbDMVX05', 'B2COMgkm'], ['CXznlK7N', 'DKJsyOTa'], ['BSRHBr1H', 'DFMr11p-'],
  ]
  return members.flatMap((m, i) => [
    `/assets/${m}-${hashes[i][0]}.js`,
    `/assets/${m}_b-${hashes[i][1]}.js`,
  ])
}
